version: '3.8'
services:
  app:
    image: webdevops/php-nginx:8.3
    volumes:
      - ./:/var/www/html
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - mysql
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: support_tracker
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
